### ISSUE TITLE
How is reorder meant to be used?

### ISSUE THREAD

**Issue by os-gabe** [granne/granne#13]
Hello,
I'm wondering what the intended use for the `reorder` method of `Granne` is. I would like to take advantage of better cache locality but I'm not quite sure when/how to use it. How can I incorporate this into my indexing workflow which currently looks like:
```
DIMENSION = 512
ELEMENT_TYPE = "angular"

builder = granne.GranneBuilder("angular")
metadata = []
for _ in range(100000):
    metadata.append("some metadata about this element")
    vec = np.random.rand(DIMENSION) - 0.5
    builder.append(vec)

builder.build()
builder.save_index(fname_idx)
builder.save_elements(fnames_elem)
```

**Comment by erik-cliqz** [comment]
Hi,

did you see the [rust documentation](https://docs.rs/granne/0.5.0/granne/struct.Granne.html#method.reorder) for this method?

The usage in Python would be something like this:
```python
index = granne.Granne(fname_idx, "angular", fnames_elem) 

order = index.reorder()
metadata = [metadata[i] for i in order]

index.save_index("{}-reorder".format(fname_idx))
index.save_elements("{}-reorder".format(fnames_elem))
```

I am not sure how well it will work for arbitrary vectors (for `SumEmbeddings` the reordering is done a bit differently and works quite ok), but feel free to try it out.

**Comment by os-gabe** [comment]
Sorry, I somehow missed that documentation. Thank you for your answer and the link - that is exactly what I needed.
