### ISSUE TITLE
Error running build_and_search.py

### ISSUE THREAD

**Issue by os-gabe** [granne/granne#3]
When running `granne/examples/py/build_and_search.py` I get the following error:
```
thread '<unnamed>' panicked at 'assertion failed: metadata.len() <= METADATA_LEN', /tmp/pip-req-build-3bq0acsr/src/hnsw/io.rs:71:5
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
<ipython-input-8-1b56a13d105e> in <module>()
     30 
     31 print("Saving to disk")
---> 32 builder.save_index(INDEX_PATH)
     33 builder.save_elements(ELEMENTS_PATH)
     34 

SystemError: Rust panic
```

I'm on Ubuntu 18.04. Let me know what other debug info would be useful.

**Comment by erik-cliqz** [comment]
Thanks for checking out the repo. Your issue should have been fixed now. Please try again, and let me know if it still does not work.

**Comment by os-gabe** [comment]
Thanks for the quick fix @erik-cliqz! The example is now working for me. I'm enjoying checking out the library found through your very interesting blog post on Indexing Billions of Text Vectors.
