### ISSUE TITLE
Query the distance between two elements

### ISSUE THREAD

**Issue by os-gabe** [granne/granne#9]
Is there a way, from Python, to query the distance between any two arbitrary elements? I know I can retrieve the vectors and compute the distance myself but I want to be sure the distance is computed with exactly the same metric that granne uses internally.

**Comment by erik-cliqz** [comment]
There is now a function for this (supporting element types `angular` and `angular_int`):
```python
import granne
import numpy as np

a = (np.random.rand(10) - 0.5)
b = (np.random.rand(10) - 0.5)

granne.compute_distance("angular", a, b)
granne.compute_distance("angular_int", a, b)
```
